// packages/render-react/src/tipRender/functionTip.tsx
import { useMemo, useRef, useState, memo } from 'react'
import { createPortal } from 'react-dom'

import { useRender } from '../context'

import type { FunctionSelectProps } from './type'
import type { FunctionTipOption } from '@shuttle-formula/render'

export type FunctionSelectComponent = (
  props: FunctionSelectProps,
) => JSX.Element
export type { FunctionSelectProps }

interface Props {
  FunctionSelect: FunctionSelectComponent
}

function FunctionTip({ FunctionSelect }: Props) {
  const { render } = useRender()
  const [tipOption, updateTipOption] = useState<FunctionTipOption>()
  const handleSelect = useRef<(functionName: string) => void>(() => {})

  const wrapper = useMemo(() => {
    const wrapper = document.createElement('div')

    render.tipRender.setFunctionPicker({
      updateTipOption,
      setOnSelect(onSelect) {
        handleSelect.current = onSelect
      },
      getRoot() {
        return wrapper
      },
    })

    return wrapper
  }, [])

  if (!tipOption) return <></>

  return createPortal(
    <FunctionSelect
      option={tipOption}
      functions={render.getOption().functions}
      onSelect={handleSelect.current}
    />,
    wrapper,
  )
}

export default memo(FunctionTip)

// packages/render-vue/src/tipRender/functionTip.vue
<script setup lang="ts">
import type { FunctionTipOption } from '@shuttle-formula/render'
import type { FunctionSelectComponent } from './type'

import { onBeforeMount, ref } from 'vue'
import useRender from '../context/useRender'

const { functionSelect } = defineProps<{
  functionSelect: FunctionSelectComponent
}>()

const tipOption = ref<FunctionTipOption>()
const onSelectRef = ref<(functionName: string) => void>()
const wrapper = ref(document.createElement('div'))
const { render } = useRender()

onBeforeMount(() => {
  render.tipRender.setFunctionPicker({
    updateTipOption(option) {
      tipOption.value = option
    },
    setOnSelect(onSelect) {
      onSelectRef.value = onSelect
    },
    getRoot() {
      return wrapper.value
    },
  })
})
</script>

<template>
  <Teleport v-if="!!tipOption" :to="wrapper">
    <functionSelect
      :option="tipOption"
      :functions="render.getOption().functions"
      :on-select="onSelectRef"
    />
  </Teleport>
</template>
