// packages/render-react/src/tipRender/variableTip.tsx
import { memo, useMemo, useRef, useState } from 'react'
import { createPortal } from 'react-dom'

import { useRender } from '../context'

import type { VariableSelectProps } from './type'
import type { VariableTipOption } from 'render'

export type VariableSelectComponent = (
  props: VariableSelectProps,
) => JSX.Element
export type { VariableSelectProps }

interface Props {
  VariableSelect: VariableSelectComponent
}

function VariableTip({ VariableSelect }: Props) {
  const { render } = useRender()
  const [tipOption, updateTipOption] = useState<VariableTipOption>()
  const handleSelect = useRef<(path: string[]) => void>(() => {})

  const wrapper = useMemo(() => {
    const wrapper = document.createElement('div')

    render.tipRender.setVariablePicker({
      updateTipOption,
      setOnSelect(onSelect) {
        handleSelect.current = onSelect
      },
      getRoot() {
        return wrapper
      },
    })

    return wrapper
  }, [])

  if (!tipOption) return <></>

  return createPortal(
    <VariableSelect
      option={tipOption}
      variables={render.getOption().variables}
      onSelect={handleSelect.current}
      getDynamicObjectByPath={render.getOption().getDynamicObjectByPath}
    />,
    wrapper,
  )
}

export default memo(VariableTip)

// packages/render-vue/src/tipRender/variableTip.vue
<script setup lang="ts">
import { onBeforeMount, ref } from 'vue'
import { VariableTipOption } from 'render'

import { VariableSelectComponent } from './type'
import useRender from '../context/useRender'

const { variableSelect } = defineProps<{
  variableSelect: VariableSelectComponent
}>()

const tipOption = ref<VariableTipOption>()
const onSelectRef = ref<(path: string[]) => void>()
const wrapper = ref(document.createElement('div'))
const { render } = useRender()

onBeforeMount(() => {
  render.tipRender.setVariablePicker({
    updateTipOption(option) {
      tipOption.value = option
    },
    setOnSelect(onSelect) {
      onSelectRef.value = onSelect
    },
    getRoot() {
      return wrapper.value
    },
  })
})
</script>

<template>
  <Teleport v-if="!!tipOption" :to="wrapper">
    <variableSelect
      :option="tipOption"
      :variables="render.getOption().variables"
      :getDynamicObjectByPath="render.getOption().getDynamicObjectByPath"
      :onSelect="onSelectRef"
    />
  </Teleport>
</template>
