// packages/render-react-antd/src/formula/functionSelect/selectPanel/group.tsx
import React, { useState } from 'react'
import { DownOutlined } from '@ant-design/icons'

interface Props {
  title: React.ReactNode
  children?: React.ReactNode
}

export default function Group({ title, children }: Props) {
  const [open, setOpen] = useState(true)

  return (
    <div className="function-select-group">
      <div className="function-select-group-header">
        <DownOutlined
          className="function-select-group-header-icon"
          onClick={() => setOpen(!open)}
          style={open ? undefined : { rotate: '-90deg' }}
        />
        <span className="function-select-group-title">{title}</span>
      </div>
      {open && <div className="function-select-group-options">{children}</div>}
    </div>
  )
}

// packages/render-vue-element-plus/src/formula/functionSelect/selectPanel/group.vue
<template>
  <div class="function-select-group">
    <div class="function-select-group-header">
      <DownOutlined
        class="function-select-group-header-icon"
        @click="open = !open"
        :style="open ? undefined : 'rotate: -90deg'"
      />
      <span class="function-select-group-title">
        <slot name="title" />
      </span>
    </div>
    <div v-if="open" class="function-select-group-options">
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import DownOutlined from '../../../components/downOutlined.vue'

defineSlots<{
  title: () => any
  default: () => any
}>()

const open = ref(true)
</script>
