// packages/render-react-antd/src/formula/functionSelect/selectPanel/option.tsx
import React, { useCallback, useState } from 'react'
import classNames from 'classnames'
import { Popover } from 'antd'

import { SelectOption } from './type'

interface Props extends SelectOption {
  className?: string
  style?: React.CSSProperties
  onClick?: (value: string) => void
  onMouseEnter?: (value: string) => void
}

export default function Option({
  className,
  style,
  value,
  label,
  extraTip,
  onClick,
  onMouseEnter,
}: Props) {
  const [visible, setVisible] = useState(false)

  const handleClick = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation()

      onClick?.(value)
      setVisible(false)
    },
    [onClick, value],
  )

  const handleMouseEnter = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation()

      onMouseEnter?.(value)
    },
    [onMouseEnter, value],
  )

  return (
    <Popover
      open={visible}
      onOpenChange={setVisible}
      content={extraTip}
      placement="left"
      trigger="hover"
      getPopupContainer={() => document.body}
    >
      <div
        className={classNames('function-select-option', className)}
        style={style}
        onClick={handleClick}
        onMouseEnter={handleMouseEnter}
      >
        <span>{label || value}</span>
      </div>
    </Popover>
  )
}

// packages/render-vue-element-plus/src/formula/functionSelect/selectPanel/option.vue
<template>
  <ElPopover
    v-model:visible="visible"
    placement="right"
    width="420px"
    :disabled="!props.extraTip"
    :show-after="200"
  >
    <template #reference>
      <div
        v-bind="attrs"
        class="function-select-option"
        @click="handleClick"
        @mouseenter="handleMouseEnter"
      >
        <span>{{ props.label || props.value }}</span>
      </div>
    </template>

    <component :is="props.extraTip" />
  </ElPopover>
</template>

<script setup lang="ts">
import { ref, useAttrs } from 'vue'
import { ElPopover } from 'element-plus'

import { SelectOption } from './type'

import 'element-plus/es/components/popover/style/css'

interface Props extends SelectOption {}

const emit = defineEmits<{
  (e: 'click', value: string): void
  (e: 'mouseenter', value: string): void
}>()

const props = defineProps<Props>()
const attrs = useAttrs()
const visible = ref(false)

const handleClick = (e: MouseEvent) => {
  e.stopPropagation()

  emit('click', props.value)
  visible.value = false
}

const handleMouseEnter = (e: MouseEvent) => {
  e.stopPropagation()

  emit('mouseenter', props.value)
}
</script>
