// packages/render-vue-element-plus/src/formula/functionSelect/description/exapmle.vue
<template>
  <div class="function-description-example">
    <Tip v-if="tip" :detail="tip" />
    <div class="function-example-use">
      <span class="function-name">@{{ props.name }}</span>
      <span>(</span>
      <span v-for="(item, index) in props.params" :key="index">
        <span class="function-params">{{ item }}</span>
        <span v-if="index !== props.params.length - 1">,&nbsp;</span>
      </span>
      <span>)</span>
    </div>
    <div class="function-example-result">
      <span>返回值: </span>
      <span class="function-result">{{ props.result }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { FunctionDescriptionExample } from '@shuttle-formula/functions'
import Tip from './tip.vue'

export interface FunctionDescriptionExampleProps extends FunctionDescriptionExample {
  name: string
}

const props = defineProps<FunctionDescriptionExampleProps>()
</script>

// packages/render-react-antd/src/formula/functionDefine/description/exapmle.tsx
import Tip from './tip'

export interface FunctionDescriptionExample {
  tip?: string
  name: string
  params: string[]
  result: string
}

export default function Example({ tip, name, params, result }: FunctionDescriptionExample) {
  return (
    <div className="function-description-example">
      {tip && <Tip detail={tip} />}
      <div className="function-example-use">
        <span className="function-name">@{name}</span>
        <span>(</span>
        {params.map((item, index) => (
          <span key={index}>
            <span className="function-params">{item}</span>
            {index !== params.length - 1 && <span>,&nbsp;</span>}
          </span>
        ))}
        <span>)</span>
      </div>
      <div className="function-example-result">
        <span>返回值: </span>
        <span className="function-result">{result}</span>
      </div>
    </div>
  )
}
