// packages/render-vue-element-plus/src/formula/renderEditor/viewPanel/function.vue
<template>
  <div class="formula-function-wrapper">
    <SelectPanel
      :options="optionGroups"
      @hoverChange="handleChangeHover"
      @clickItem="handleClick"
    />
    <div v-if="hoverFunction?.description" class="formula-function-example">
      <FunctionDescriptionRender
        v-bind="hoverFunction.description"
        :name="hoverFunction.label || ''"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import {
  WithLabelFunction,
  FunctionDescription,
  FunctionGroup,
} from '@shuttle-formula/functions'

import FunctionDescriptionRender from '../../functionSelect/description/index.vue'
import SelectPanel from '../../functionSelect/selectPanel/index.vue'
import {
  SelectGroup,
  SelectOption,
} from '../../functionSelect/selectPanel/type'

interface Props {
  functions?:
    | Record<string, WithLabelFunction<FunctionDescription>>
    | FunctionGroup<FunctionDescription>[]
}

const props = defineProps<Props>()
const emit = defineEmits<{
  (
    e: 'pickFunction',
    fnKey: string,
    fn: WithLabelFunction<FunctionDescription>,
  ): void
}>()
const hoverFunction = ref<WithLabelFunction<FunctionDescription>>()

const optionGroups = computed(() => {
  if (!props.functions) return []

  if (Array.isArray(props.functions)) {
    const optionGroups: SelectGroup[] = props.functions.map((group) => {
      return {
        id: group.id,
        label: group.label,
        options: recordsToOptions(group.functions),
      }
    })

    return optionGroups
  }

  return recordsToOptions(props.functions)
})

const findFunction = (functionKey: string) => {
  if (!props.functions) return

  if (Array.isArray(props.functions)) {
    for (const group of props.functions) {
      if (group.functions[functionKey]) {
        return group.functions[functionKey]
      }
    }
  } else {
    return props.functions[functionKey]
  }
}

const handleChangeHover = (value?: string) => {
  if (!value) {
    hoverFunction.value = undefined
    return
  }

  const func = findFunction(value)
  hoverFunction.value = func
}

const handleClick = (option: SelectOption) => {
  const func = findFunction(option.value)
  if (func) {
    emit('pickFunction', option.value, func)
  }
}

function recordsToOptions(
  functionMap: Record<string, WithLabelFunction<FunctionDescription>>,
) {
  const options: SelectOption[] = []

  for (const key in functionMap) {
    options.push({
      value: key,
      label: functionMap[key].label || '',
    })
  }

  return options
}
</script>

// packages/render-react-antd/src/formula/renderEditor/viewPanel/function.tsx
import { useCallback, useMemo, useState } from 'react'
import {
  WithLabelFunction,
  FunctionDescription,
  FunctionGroup,
} from '@shuttle-formula/functions'

import FunctionDescriptionRender from '../../functionSelect/description'
import SelectPanel from '../../functionSelect/selectPanel'
import {
  SelectGroup,
  SelectOption,
} from '../../functionSelect/selectPanel/type'

interface Props {
  functions?:
    | Record<string, WithLabelFunction<FunctionDescription>>
    | FunctionGroup<FunctionDescription>[]
  onPickFunction?: (
    fnKey: string,
    fn: WithLabelFunction<FunctionDescription>,
  ) => void
}

export default function FormulaFunction({ functions, onPickFunction }: Props) {
  const [hoverFunction, setHoverFunction] =
    useState<WithLabelFunction<FunctionDescription>>()

  const optionGroups = useMemo(() => {
    if (!functions) return []

    if (Array.isArray(functions)) {
      const optionGroups: SelectGroup[] = functions.map((group) => {
        return {
          id: group.id,
          label: group.label,
          options: recordsToOptions(group.functions),
        }
      })

      return optionGroups
    }

    return recordsToOptions(functions)
  }, [functions])

  const findFunction = useCallback(
    (functionKey: string) => {
      if (!functions) return

      if (Array.isArray(functions)) {
        for (const group of functions) {
          if (group.functions[functionKey]) {
            return group.functions[functionKey]
          }
        }
      } else {
        return functions[functionKey]
      }
    },
    [functions],
  )

  const handleChangeHover = useCallback(
    (value?: string) => {
      if (!value) {
        setHoverFunction(undefined)
        return
      }

      const func = findFunction(value)

      setHoverFunction(func)
    },
    [findFunction],
  )

  const handleClick = useCallback(
    (option: SelectOption) => {
      const func = findFunction(option.value)
      if (func) {
        onPickFunction?.(option.value, func)
      }
    },
    [onPickFunction, findFunction],
  )

  return (
    <div className="formula-function-wrapper">
      <SelectPanel
        options={optionGroups}
        onHoverChange={handleChangeHover}
        onClickItem={handleClick}
      />
      {hoverFunction?.description && (
        <div className="formula-function-example">
          <FunctionDescriptionRender
            {...hoverFunction.description}
            name={hoverFunction.label || ''}
          />
        </div>
      )}
    </div>
  )
}

function recordsToOptions(
  functionMap: Record<string, WithLabelFunction<FunctionDescription>>,
) {
  const options: SelectOption[] = []

  for (const key in functionMap) {
    options.push({
      value: key,
      label: functionMap[key].label || '',
    })
  }

  return options
}
