// packages/render-vue-element-plus/src/formula/renderEditor/viewPanel/variable.vue
<template>
  <div class="formula-variable-wrapper">
    <FormulaVariablePickerPanel
      v-bind="attrs"
      :openPath="openPath"
      :openOnSelectPath="false"
      @open="(v) => (openPath = v)"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, useAttrs } from 'vue'
import FormulaVariablePickerPanel from '../../variableSelect/formulaVariablePickerPanel.vue'

const openPath = ref<string[]>()
const attrs = useAttrs()
</script>

// packages/render-react-antd/src/formula/renderEditor/viewPanel/variable.tsx
import { useState } from 'react'
import FormulaVariablePickerPanel, { VariablePickerPanelProps } from '../../variableSelect/formulaVariablePickerPanel'

interface Props extends Omit<VariablePickerPanelProps, 'variablePath' | 'openOnSelectPath' | 'openPath' | 'onOpen'> {}

export default function FormulaVariable(props: Props) {
  const [openPath, setOpenPath] = useState<string[]>()

  return (
    <div className="formula-variable-wrapper">
      <FormulaVariablePickerPanel {...props} openPath={openPath} openOnSelectPath={false} onOpen={setOpenPath} />
    </div>
  )
}
