// packages/render-vue-element-plus/src/formula/functionSelect/description/define.vue
<template>
  <div class="function-description-define">
    <span class="function-name">@{{ props.name }}</span>
    <span>(</span>
    <span v-for="(item, index) in props.paramsList" :key="index">
      <span class="function-params">{{ item }}</span>
      <span v-if="index !== props.paramsList.length - 1">,&nbsp;</span>
    </span>
    <span>)</span>
    <span>&nbsp;&nbsp;-&gt;&nbsp;&nbsp;</span>
    <span class="function-result">{{ props.result }}</span>
  </div>
</template>
<script setup lang="ts">
import { FunctionDescriptionDefine } from '@shuttle-formula/functions'

export interface FunctionDescriptionDefineProps extends FunctionDescriptionDefine {
  name: string
}

const props = defineProps<FunctionDescriptionDefineProps>()
</script>

// packages/render-react-antd/src/formula/functionSelect/description/define.tsx
import { FunctionDescriptionDefine } from '@shuttle-formula/functions'

export interface FunctionDescriptionDefineProps
  extends FunctionDescriptionDefine {
  name: string
}

export default function Define({
  name,
  paramsList,
  result,
}: FunctionDescriptionDefineProps) {
  return (
    <div className="function-description-define">
      <span className="function-name">@{name}</span>
      <span>(</span>
      {paramsList.map((item, index) => (
        <span key={index}>
          <span className="function-params">{item}</span>
          {index !== paramsList.length - 1 && <span>,&nbsp;</span>}
        </span>
      ))}
      <span>)</span>
      <span>&nbsp;&nbsp;-&gt;&nbsp;&nbsp;</span>
      <span className="function-result">{result}</span>
    </div>
  )
}
