// packages/render-vue-element-plus/src/formula/renderUsePlugin.vue
<template>
  <FormulaRender
    :class="props.class"
    :style="props.style"
    :code="props.code"
    :functions="props.functions"
    :disabled="props.disabled"
    :variables="formulaVariables"
    :getDynamicObjectByPath="getDynamicObjectByPath"
    :accept="handleAccept"
  />
</template>

<script lang="ts">
import type { FormulaRenderProps } from './render.vue'

export interface FormulaRenderUsePluginProps extends Omit<
  FormulaRenderProps,
  'getDynamicObjectByPath' | 'accept' | 'variables'
> {
  accept?: {
    defines: VariablePlugin.Define[]
    exclude?: boolean
  }
  variables?: Record<string, VariablePlugin.Define>
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { WithDynamicVariable } from '@shuttle-formula/render'
import {
  variablePluginManager,
  VariablePlugin,
} from '@shuttle-formula/variable-plugin'

import FormulaRender from './render.vue'

const props = defineProps<FormulaRenderUsePluginProps>()

const formulaVariables = computed(() =>
  variablePluginManager.recordToFormula(props.variables || {}),
)

const getDynamicObjectByPath =
  variablePluginManager.createGetDynamicObjectByPath()

const handleAccept = (returnType: WithDynamicVariable) => {
  if (!props.accept?.defines.length) return

  const acceptFn = variablePluginManager.createAccept(
    props.accept.defines,
    props.accept.exclude,
  )
  return acceptFn(returnType)
}
</script>

// packages/render-react-antd/src/formula/renderUsePlugin.tsx
import { useMemo } from 'react'
import { WithDynamicVariable } from '@shuttle-formula/render'
import {
  variablePluginManager,
  VariablePlugin,
} from '@shuttle-formula/variable-plugin'

import useEffectCallback from '../hooks/useEffectCallback'
import FormulaRender, { FormulaRenderProps } from './render'

export interface FormulaRenderUsePluginProps extends Omit<
  FormulaRenderProps,
  'getDynamicObjectByPath' | 'accept' | 'variables'
> {
  accept?: {
    defines: VariablePlugin.Define[]
    exclude?: boolean
  }
  variables?: Record<string, VariablePlugin.Define>
}

export default function RenderUsePlugin({
  accept,
  variables,
  ...extra
}: FormulaRenderUsePluginProps) {
  const formulaVariables = useMemo(
    () => variablePluginManager.recordToFormula(variables || {}),
    [variables],
  )

  const getDynamicObjectByPath = useMemo(
    () => variablePluginManager.createGetDynamicObjectByPath(),
    [],
  )

  const handleAccept = useEffectCallback(
    (returnType: WithDynamicVariable) => {
      if (!accept?.defines.length) return

      const acceptFn = variablePluginManager.createAccept(
        accept.defines,
        accept.exclude,
      )
      return acceptFn(returnType)
    },
    [accept],
  )

  return (
    <FormulaRender
      {...extra}
      variables={formulaVariables}
      getDynamicObjectByPath={getDynamicObjectByPath}
      accept={handleAccept}
    />
  )
}
