// packages/render-vue-element-plus/src/formula/variableSelect/cascaderPanel/index.vue
<template>
  <div :class="['cascader-panel-container', props.class]" :style="props.style">
    <CascaderSinglePanel
      v-bind="props"
      :openPath="_openPath"
      :selectPath="_selectPath"
      @select="handleSelect"
      @open="handleOpen"
    />
  </div>
</template>

<script lang="ts">
export type CascaderOption<T extends Record<string, any>> = {
  key: string
  title: string
  isLeaf?: boolean
  isDisabled?: boolean
  children?: CascaderOption<T>[]
} & T

export interface CascaderPanelProps<T extends Record<string, any>> {
  style?: string
  class?: string
  wrapperStyle?: string
  wrapperClassName?: string
  options: CascaderOption<T>[]
  selectPath?: string[]
  openPath?: string[]
  openOnSelectPath?: boolean
  loadMore?: (option: CascaderOption<T>) => Promise<void>
}
</script>

<script setup lang="ts" generic="T extends Record<string, any>">
import { ref, watch } from 'vue'
import CascaderSinglePanel from './panel.vue'

const props = defineProps<CascaderPanelProps<T>>()
const emit = defineEmits<{
  (e: 'open', path: string[], option?: CascaderOption<T>): void
  (e: 'select', path: string[], option: CascaderOption<T>): void
}>()

const _openPath = ref(props.openPath)
const _selectPath = ref(props.selectPath)

const handleOpen = (path: string[], option?: CascaderOption<T>) => {
  _openPath.value = path
  emit('open', path, option)
}

const handleSelect = (path: string[], option: CascaderOption<T>) => {
  _selectPath.value = path
  emit('select', path, option)
}

watch(
  () => props.selectPath,
  (newVal) => {
    if (newVal) {
      handleOpen(newVal)
    }
  },
  { immediate: true },
)
</script>

<style lang="scss">
.cascader-panel-container {
  display: flex;
  flex-direction: row;
  flex-wrap: nowrap;
  max-width: 60vw;
  overflow-x: auto;
}

.cascader-panel-wrapper {
  display: flex;
  flex-direction: column;
  padding: 4px 0;
  width: 140px;
  min-width: 140px;
  &:not(:last-child) {
    border-right: 1px solid #ccc;
  }

  .cascader-panel-item {
    display: flex;
    flex-direction: row;
    padding: 2px 4px;
    margin: 2px 0;
    border-radius: 4px;
    align-items: center;
    cursor: pointer;

    .cascader-panel-title {
      flex: 1;
    }

    &.is-selected {
      color: #1677ff;
    }

    &:hover {
      background-color: #f2f3f5;
    }

    &.is-disabled {
      background-color: #f2f3f5;
      color: #d9d9d9;
      cursor: not-allowed;
    }

    &.is-open {
      background-color: rgb(232, 243, 255);
    }

    .cascader-panel-next-icon {
      border-radius: 50%;
      padding: 2px;
      font-size: 0.75rem;
      cursor: pointer;
      &:hover {
        background-color: #fff;
      }
    }

    .cascader-panel-loading-icon {
      color: #165dff;
    }
  }
}
</style>

// packages/render-react-antd/src/formula/variableSelect/cascaderPanel/index.tsx
import { useEffect, useMemo, useState } from 'react'
import { RightOutlined, LoadingOutlined } from '@ant-design/icons'
import classNames from 'classnames'
import useEffectCallback from '../../../hooks/useEffectCallback'
import useHold from '../../../hooks/useHold'
import useRefEffect from '../../../hooks/useRefEffect'

import './index.scss'

export type CascaderOption<T extends Record<string, any>> = {
  key: string
  title: React.ReactNode
  isLeaf?: boolean
  isDisabled?: boolean
  children?: CascaderOption<T>[]
} & T

export interface CascaderPanelProps<T extends Record<string, any>> {
  style?: React.CSSProperties
  className?: string
  wrapperStyle?: React.CSSProperties
  wrapperClassName?: string
  options: CascaderOption<T>[]
  selectPath?: string[]
  openPath?: string[]
  openOnSelectPath?: boolean
  onSelect?: (selectPath: string[], option: CascaderOption<T>) => void
  onOpen?: (openPath: string[], option?: CascaderOption<T>) => void
  loadMore?: (option: CascaderOption<T>) => Promise<void>
}

export default function CascaderPanel<T extends Record<string, any>>({
  style,
  className,
  openPath,
  selectPath,
  openOnSelectPath,
  onSelect,
  onOpen,
  ...panelProps
}: CascaderPanelProps<T>) {
  const [_openPath, setOpenPath] = useHold(openPath)
  const [_selectPath, setSelectPath] = useHold(selectPath)

  const handleOpen = useEffectCallback(
    (path: string[], option?: CascaderOption<T>) => {
      setOpenPath(path)
      onOpen?.(path, option)
    },
    [onOpen],
  )

  const handleSelect = useEffectCallback(
    (path: string[], option: CascaderOption<T>) => {
      setSelectPath(path)
      onSelect?.(path, option)
    },
    [onSelect],
  )

  useRefEffect(
    [openOnSelectPath, onOpen],
    (
      refOpenOnSelectPath?: boolean,
      refOnOpen?: (path: string[], option?: CascaderOption<T>) => void,
    ) => {
      if (!refOpenOnSelectPath) return

      if (!selectPath) return

      setOpenPath(selectPath)
      refOnOpen?.(selectPath)
    },
    [selectPath?.join('')],
  )

  return (
    <div
      className={classNames('cascader-panel-container', className)}
      style={style}
    >
      <CascaderSinglePanel
        openPath={_openPath}
        selectPath={_selectPath}
        onSelect={handleSelect}
        onOpen={handleOpen}
        {...panelProps}
      />
    </div>
  )
}

function CascaderSinglePanel<T extends Record<string, any>>({
  options,
  wrapperClassName,
  wrapperStyle,
  selectPath,
  openPath,
  onSelect,
  onOpen,
  loadMore,
}: Omit<CascaderPanelProps<T>, 'style' | 'className' | 'openOnSelectPath'>) {
  const [openNextOption, setOpenNextOption] = useState<CascaderOption<T>>()
  const [loadingMap, setLoadingMap] = useState<Record<string, boolean>>({})

  const handleLoadMore = useEffectCallback(
    async (option: CascaderOption<T>) => {
      if (!loadMore) return

      setLoadingMap((old) => ({
        ...old,
        [option.key]: true,
      }))

      await loadMore(option)

      setLoadingMap((old) => ({
        ...old,
        [option.key]: false,
      }))
    },
    [loadMore],
  )

  const handleOpenNext = useEffectCallback(
    (path: string[], option?: CascaderOption<T>) => {
      if (option && !option.isLeaf && !option.children?.length) {
        handleLoadMore(option)
      }

      onOpen?.(path, option)
    },
    [onOpen],
  )

  useEffect(() => {
    if (!openPath?.length) {
      setOpenNextOption(undefined)
      return
    }

    const openOption = options.find((option) => option.key === openPath[0])

    if (openOption?.children?.length) {
      setOpenNextOption(openOption)
    } else {
      setOpenNextOption(undefined)
    }
  }, [options, openPath, loadingMap])

  const handleSelect = useEffectCallback(
    (path: string[], option: CascaderOption<T>) => {
      if (option.isDisabled) return

      onSelect?.(path, option)
    },
    [onSelect],
  )

  const nextSelectPath = useMemo(() => {
    if (!openNextOption || !selectPath?.length) return []

    if (openNextOption.key !== selectPath[0]) return []

    return selectPath.slice(1)
  }, [openNextOption, selectPath])

  const nextOpenPath = useMemo(() => {
    if (!openNextOption || !openPath?.length) return []

    if (openNextOption.key !== openPath[0]) return []

    return openPath.slice(1)
  }, [openNextOption, openPath])

  return (
    <>
      <div
        className={classNames('cascader-panel-wrapper', wrapperClassName)}
        style={wrapperStyle}
      >
        {options.map((option) => (
          <div
            className={classNames(
              'cascader-panel-item',
              selectPath?.[0] === option.key && 'is-selected',
              openNextOption?.key === option.key && 'is-open',
              option.isDisabled && 'is-disabled',
            )}
            key={option.key}
          >
            <div
              className="cascader-panel-title"
              onClick={() => handleSelect([option.key], option)}
            >
              {option.title}
            </div>

            {loadingMap[option.key] ? (
              <LoadingOutlined className="cascader-panel-loading-icon" spin />
            ) : (
              (option.children?.length || (loadMore && !option.isLeaf)) && (
                <RightOutlined
                  className="cascader-panel-next-icon"
                  onClick={() =>
                    handleOpenNext(
                      openNextOption?.key === option.key ? [] : [option.key],
                      option,
                    )
                  }
                />
              )
            )}
          </div>
        ))}
      </div>
      {openNextOption?.children && (
        <CascaderSinglePanel
          wrapperClassName={wrapperClassName}
          wrapperStyle={wrapperStyle}
          options={openNextOption.children}
          selectPath={nextSelectPath}
          openPath={nextOpenPath}
          onSelect={(path, option) =>
            handleSelect([openNextOption.key, ...path], option)
          }
          onOpen={(path, option) =>
            handleOpenNext([openNextOption.key, ...path], option)
          }
          loadMore={loadMore}
        />
      )}
    </>
  )
}
