// packages/render-react-antd/src/formula/render.tsx
import { VariableDefine } from '@shuttle-formula/core'
import {
  Provider,
  VariableTip,
  FunctionTip,
} from '@shuttle-formula/render-react'

import type {
  FunctionGroup,
  WithLabelFunction,
  FunctionDescription,
} from '@shuttle-formula/functions'
import type {
  GetDynamicObjectByPath,
  WithDynamicVariable,
} from '@shuttle-formula/render'

import FunctionSelect from './functionSelect'
import VariableSelect from './variableSelect'
import OnChange, { OnChangeProps } from './onChange'
import RenderEditor from './renderEditor'

interface Props extends OnChangeProps {
  className?: string
  style?: React.CSSProperties
  code?: string
  getDynamicObjectByPath?: GetDynamicObjectByPath
  accept?:
    | VariableDefine.Desc
    | VariableDefine.Desc[]
    | ((returnType: VariableDefine.Desc) => string | undefined)
  variables?: Record<string, WithDynamicVariable>
  functions?:
    | Record<string, WithLabelFunction<FunctionDescription>>
    | FunctionGroup<FunctionDescription>[]
  disabled?: boolean
}

export default function RenderFormula({
  className,
  style,
  code,
  accept,
  variables,
  functions,
  disabled,
  onAstChange,
  onTokenChange,
  getDynamicObjectByPath,
}: Props) {
  return (
    <Provider
      disabled={disabled}
      code={code}
      variables={variables}
      functions={functions}
      getDynamicObjectByPath={getDynamicObjectByPath}
    >
      <RenderEditor
        style={style}
        className={className}
        accept={accept}
        disabled={disabled}
      />
      <VariableTip VariableSelect={VariableSelect} />
      <FunctionTip FunctionSelect={FunctionSelect} />
      <OnChange onAstChange={onAstChange} onTokenChange={onTokenChange} />
    </Provider>
  )
}

// packages/render-vue-element-plus/src/formula/render.vue
<template>
  <Provider
    :disabled="disabled"
    :code="code"
    :variables="variables"
    :functions="functions"
    :getDynamicObjectByPath="getDynamicObjectByPath"
  >
    <RenderEditor
      :style="style"
      :class="class"
      :accept="accept"
      :disabled="disabled"
    />
    <VariableTip :variableSelect="VariableSelect" />
    <FunctionTip :functionSelect="FunctionSelect" />
    <OnChange
      @astChange="(v) => emit('astChange', v)"
      @tokenChange="(v) => emit('tokenChange', v)"
    />
  </Provider>
</template>

<script setup lang="ts">
import { VariableDefine } from '@shuttle-formula/core'
import { Provider, VariableTip, FunctionTip } from '@shuttle-formula/render-vue'

import type {
  FunctionGroup,
  WithLabelFunction,
  FunctionDescription,
} from '@shuttle-formula/functions'
import type {
  GetDynamicObjectByPath,
  WithDynamicVariable,
} from '@shuttle-formula/render'

import FunctionSelect from './functionSelect/index.vue'
import VariableSelect from './variableSelect/index.vue'
import OnChange, { TokenInfo, AstInfo } from './onChange/index.vue'
import RenderEditor from './renderEditor/index.vue'

interface Props {
  class?: string
  style?: string
  code?: string
  getDynamicObjectByPath?: GetDynamicObjectByPath
  accept?:
    | VariableDefine.Desc
    | VariableDefine.Desc[]
    | ((returnType: WithDynamicVariable) => string | undefined)
  variables?: Record<string, WithDynamicVariable>
  functions?:
    | Record<string, WithLabelFunction<FunctionDescription>>
    | FunctionGroup<FunctionDescription>[]
  disabled?: boolean
}

defineProps<Props>()
const emit = defineEmits<{
  (e: 'tokenChange', tokenInfo: TokenInfo): void
  (e: 'astChange', astInfo: AstInfo): void
}>()
</script>
