// packages/render-vue-element-plus/src/formula/variableSelect/index.vue
<template>
  <FormulaVariablePickerPanel
    :variablePath="props.option.path"
    :variables="props.option.startVariable"
  />
</template>

<script lang="ts">
import type { VariableTipOption } from '@shuttle-formula/render'
import { VariablePickerPanelProps } from './formulaVariablePickerPanel.vue'

interface BaseProps {
  option: VariableTipOption
}

export interface VariableSelectProps
  extends
    Omit<VariablePickerPanelProps, 'variablePath' | 'variables'>,
    BaseProps {}
</script>

<script setup lang="ts">
import FormulaVariablePickerPanel from './formulaVariablePickerPanel.vue'

const props = defineProps<BaseProps>()
</script>

// packages/render-react-antd/src/formula/variableSelect/index.tsx
import type { VariableTipOption } from '@shuttle-formula/render'
import FormulaVariablePickerPanel, {
  VariablePickerPanelProps,
} from './formulaVariablePickerPanel'

export interface VariableSelectProps
  extends Omit<VariablePickerPanelProps, 'variablePath' | 'variables'> {
  option: VariableTipOption
}

export default function VariableSelect({
  option,
  ...extra
}: VariableSelectProps) {
  return (
    <FormulaVariablePickerPanel
      variablePath={option.path}
      variables={option.startVariable}
      {...extra}
    />
  )
}
