// packages/render-react/src/render/index.tsx
import { useLayoutEffect, useRef, forwardRef, useImperativeHandle } from 'react'

import { useRender } from '../context'

import type { Render } from 'render'
import type { ForwardedRef } from 'react'

interface Props {
  style?: React.CSSProperties
  className?: string
}

function RenderUseReact(
  { style, className }: Props,
  ref?: ForwardedRef<Render>,
) {
  const wrapperRef = useRef<HTMLDivElement>(null)

  const { render } = useRender()

  useImperativeHandle(ref, () => render, [])

  useLayoutEffect(() => {
    if (!wrapperRef.current) return

    render.mount(wrapperRef.current)
  }, [])

  return (
    <div
      style={{ display: 'flex', ...style }}
      className={className}
      ref={wrapperRef}
    />
  )
}

export default forwardRef(RenderUseReact)

// packages/render-vue/src/render/index.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import useRender from '../context/useRender'

const wrapper = ref<HTMLElement>()
const { render } = useRender()

onMounted(() => {
  if (!wrapper.value) return

  render.mount(wrapper.value)
})
</script>

<template>
  <div ref="wrapper" style="display: flex" />
</template>
